### ISSUE TITLE
to change cluster background 

### ISSUE THREAD

**Issue by StepAlexander** [Esri/esri-leaflet-cluster#1]
I was wondering if you could advise on the following question. I created the clustered feature layer 
and used custom styles (as in this example http://esri.github.io/esri-leaflet/examples/styling-clusters.html ). I have a UI which allows a user to 'filter' clusters for by specific attribute (via <clusteredfeaturelayer>.setWhere method). it works fine. Would it be possible to change the background color for those filtered clustres  as well? Thank you.

**Comment by jgravois** [comment]
sorry i didnt see your question until now. the short answer is **yes**, _its possible_.

i couldn't figure out a more clever way to do it than looping through each and every `L.markerCluster` when features are reloaded and:
- flagging them as dirty
- assigning a different `iconCreateFunction` to utilize when updating their icon.

http://jsbin.com/xalaxo/edit?html,output

``` js
// adapted from logic originally found in L.markerClusterGroup._refreshClustersIcons()
// https://github.com/Leaflet/Leaflet.markercluster/blob/master/src/MarkerClusterGroup.js#L969-L975

myClusteredFeatureLayer.cluster._featureGroup.eachLayer(function (c) {
  if (c instanceof L.MarkerCluster) {
    c._iconNeedsUpdate = true;
    c._group.options.iconCreateFunction = function (cluster) {
      var count = cluster.getChildCount();
      return new L.divIcon({
        html: count,
        className:'cluster orange-cluster',
        iconSize: null
      });
    }
    c.createIcon();
    c._updateIcon();
 }
});
```

as you can see, this involves traversing some private properties, so _use at your own risk_.
