### ISSUE TITLE
esri-leaflet-cluster plugin not working along with esri-leaflet-renderers

### ISSUE THREAD

**Issue by PriyeshT** [Esri/esri-leaflet-cluster#18]
I am using esri-leaflet-cluster plugin to load a cluster feature layer. The feature layer has many icons which are I am trying to render using the esri-leaflet-renderers plugin. As the map service that is used to load the feature layer has the drawing info, we would want to use it to display the icons. 

When using the esri-leaflet-renderers alone, the icons are rendered as required. When I try to use it with the cluster feature layer, I get the default icon markers instead of the icons defined in the map service. 

Could you let me know what might be the issue and how I can use both the plugins together. Basically my requirement is to use the icons that are rendered by the map feature layer instead of the default marker icon.

**Comment by jgravois** [comment]
the renderers plugin currently only extends `L.esri.featureLayer`, this is why none of the custom logic is applied when you create an instance of `L.esri.Cluster.featureLayer`.

it seems like a sensible request to me to make sure the two plugins can be integrated, so i'm happy to look into it.  in the meantime, you'll have to either take a stab at it yourself or define a renderer programmatically that is equivalent to what is defined for the service.

**Comment by PriyeshT** [comment]
Thanks for the clarification. 

Currently, I am using the pointToLayer function to display the custom icons that I need. I will take a look into renderers plugin to see what can be done to make it work with Clusters.

**Comment by KuraiShinobi** [comment]
+ 1 for this, new to leaflet and npm but keen to help where I can if someone has any pointers

**Comment by jgravois** [comment]
greetings @KuraiShinobi!

the crux of [`esri-leaflet-renderers`](https://github.com/Esri/esri-leaflet-renderers) is that it triggers additional logic to fire when a `FeatureLayer` is initialized via Leaflet's own [`.addInitHook()`](https://leafletjs.com/reference.html#class-addinithook)

the first thing to try would be to attempt to extend `L.esri.Cluster.FeatureLayer` in [exactly the same way](https://github.com/Esri/esri-leaflet-renderers/blob/cc9808cbe143b4349f452f8f04e8b60d2bdfa506/src/FeatureLayerHook.js#L7-L202) and _see what happens_.

![changing stuff](https://pbs.twimg.com/media/Cf7eHZ1W4AEeZJA.jpg:large)

**Comment by shawnmgoulet** [comment]
Does anyone here know if this

> the first thing to try would be to attempt to extend `L.esri.Cluster.FeatureLayer` in exactly the same way and _see what happens_.

has been explored or still hanging?

I'm needing to cluster points, so I'm thinking a workaround would be to use the source as geoJSON and just cluster directly in Leaflet?

**Comment by zubairkhanafridi** [comment]
Hi, i am also facing this issue, is there any work around for this issue or an alternate solution?
