### ISSUE TITLE
Add types declarations

### ISSUE THREAD

**Issue by JulianKowalczuk** [Esri/esri-leaflet-cluster#22]
As in topic. Since Typescript is popular framework and esri-leaflet is typed, it would be nice to have it this package too.

**Comment by jgravois** [comment]
this plugin doesn't expose any unique options. what could we provide typings for?

https://www.npmjs.com/package/@types/esri-leaflet
https://www.npmjs.com/package/@types/leaflet.markercluster

**Comment by JulianKowalczuk** [comment]
But for example eachActiveFeature method is missing, while docs says it's inherited from FeatureLayer.

And btw typing for esri-leaflet is outdated on npm

**Comment by jgravois** [comment]
> But for example `eachActiveFeature` method is missing.

I'm not sure what you're talking about. `eachActiveFeature` is definitely present in the [typings](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/esri-leaflet/index.d.ts#L472) for esri-leaflet.

to be honest, i'm not sure how a person is supposed to declare inheritance in a this type of situation. maybe something like this?

```ts
interface Custom extends L.esri.FeatureLayer, L.markerCluster;

const myClusters:Custom = L.esri.Cluster.featureLayer();
```

> And btw typing for esri-leaflet is outdated on npm

that's a pretty typical state of affairs for typings for non TypeScript projects unfortunately.

I personally don't have the bandwidth (or motivation) to take ownership of maintaining typings for Esri Leaflet. That means its up to the TypeScript developer community. Pull requests are always welcome.

**Comment by JulianKowalczuk** [comment]
I've created issue about upgrade need of esri-leaflet typing package with guy who pushed last version attached. With updated definitions, solution of combining types from these two libraries fits for me.
