### ISSUE TITLE
Facing issue to install from npm

### ISSUE THREAD

**Issue by zzBNSF** [Esri/esri-leaflet-cluster#24]
We are developing a web map application using ESRI Leaflet, and like to implement the point cluster using esri-leaflet-cluster library. We have downloaded the library from [http://registry.npmjs.org/esri-leaflet-cluster/-/esri-leaflet-cluster-2.0.0.tgz](url) into our Artifatory. But this version seems to be a beta version, and has following dependencies per this link, [http://registry.npmjs.org/esri-leaflet-cluster](url).

```
"dependencies": {
    "esri-leaflet": "^2.0.0",
    "leaflet": "^1.0.0-rc.3",
    "leaflet.markercluster": "git+https://github.com/Leaflet/Leaflet.markercluster.git#v1.0.0-rc.1"
},
```

When we run ‘npm install’, it will try to reach out to the above github link for leaflet.markercluster install, which will be blocked by our company firewall. 

However, package.json on esri-leaflet-cluster GitHub repo has the correct dependencies as below.

```
"dependencies": {
    "esri-leaflet": "^2.0.0",
    "leaflet": "^1.0.0",
    "leaflet.markercluster": "^1.0.0"
},
```

Can you help update the library on npmjs registry to reflect the latest?

**Comment by gavinr** [comment]
@zzBNSF Upon a cursory glace, yes it looks like the changes from https://github.com/Esri/esri-leaflet-cluster/pull/20 have not been pushed into a Release. @jgravois any reason we shouldn't push your changes out to a v2.0.1 (or v2.1.0?)?

**Comment by jgravois** [comment]
`v2.0.1` :shipit:

**Comment by zzBNSF** [comment]
@jgravois Can you please upload the latest to npm, and ensure no dependencies are from GitHub link? Thanks.

**Comment by jgravois** [comment]
no, but @gavinr can.

**Comment by zzBNSF** [comment]
Thanks, @jgravois.
@gavinr when would you be able to help with the npm upload? Our project is currently blocked by the issue. Thanks.

**Comment by jgravois** [comment]
to be fair, your problem is that your company firewall is currently blocking requests to GitHub. I suggest you look into that while you're waiting for @gavinr to publish another release of this package on npm.

**Comment by zzBNSF** [comment]
I already talked to our DevOps team about this, and they cannot do that due to the security policy put in place. Can you help upload v2.0.0 release version to npm? The current npm version looks like a beta version since it depends on -rc version for leaflet and leaflet.markercluster. Thanks.

**Comment by gavinr** [comment]
v2.0.1 published to npm.
