### ISSUE TITLE
The way to draw near 340000 features

### ISSUE THREAD

**Issue by NepipenkoIgor** [Esri/esri-leaflet-cluster#27]
Hi all. I need to solve problem and show near 340000 on esri leaflet map . Now i use cluster and its work amazing  during i have near 5000 points
 This is snippet of code where i try to add layer .  
```
    const featureLayer = L.esri.Cluster.featureLayer({
      url: `${this.currentServiceURL}/${id}`,
      renderer: new L.Canvas(),
      simplifyFactor: 0.35,
    });
      featureLayer.addTo(this.lMap);
```
Could you give suggestions in which way could i solve problem ??

**Comment by jgravois** [comment]
> Could you give suggestions in which way could i solve problem ??

yup. you'd need to rewrite this plugin to use something like https://github.com/mapbox/supercluster

related: #14

**Comment by NepipenkoIgor** [comment]
@jgravois Thanks. I will try
