### ISSUE TITLE
node-sass at v4.7 - Build Failed

### ISSUE THREAD

**Issue by gavinr** [Esri/esri-leaflet-cluster#32]
Why do we have [`node-sass` locked at v4.7](https://github.com/Esri/esri-leaflet-cluster/commit/983c291ea84da7f7e7d7c3467a6b2370b15c370c)? I'm guessing there was some sort of security issue at the time @jgravois? As-is I get an error when I run `npm install` and it tries to install `node-sass` ... can we change this back to `"node-sass": "^4.9.0",`?

```
Done Building Project "C:\.....\esri-leaflet-cluster\node_modules\node-sass\build\binding.vcxproj" (default targets) -- FAILED.

Done Building Project "C:\.....\esri-leaflet-cluster\node_modules\node-sass\build\binding.vcxproj.metaproj" (default targets) -- FAILED.

Done Building Project "C:\.....\esri-leaflet-cluster\node_modules\node-sass\build\binding.sln" (default targets) -- FAILED.

Build FAILED.
```

**Comment by jgravois** [comment]
i have no clue. upgrading should definitely be safe.
