### ISSUE TITLE
Odd clustering behavior on zoom out then zoom in - cellEnter errors

### ISSUE THREAD

**Issue by gavinr** [Esri/esri-leaflet-cluster#34]
On the sample debug page, when zooming out the clustering acts as expected, but when zooming back in it does not and I'm getting errors like:

```
Uncaught TypeError: this.cellEnter is not a function
```

https://screencast-o-matic.com/watch/cY13qiCN9e

Possibly related or duplicate of https://github.com/Esri/esri-leaflet/pull/1204 ?

**Comment by gavinr** [comment]
Note that the errors do not happen if you switch to using the previous version (https://unpkg.com/esri-leaflet@2.3.3/dist), so I do think it's related to v2.4.0 and https://github.com/Esri/esri-leaflet/pull/1204

**Comment by francharbo** [comment]
That is exactly the error I had before making [Esri/esri-leaflet#1204](https://github.com/Esri/esri-leaflet/pull/1204)
This is not exclusive to clusterLayer but to all kind of featureLayer
