### ISSUE TITLE
Where clause is not always persisting

### ISSUE THREAD

**Issue by francharbo** [Esri/esri-leaflet-cluster#52]
When using the clusterlayer with a where clause on a feature layer,
the where clause is not always persisted.

This seems like this issue on esri-leaflet : [https://github.com/Esri/esri-leaflet/issues/1196](https://github.com/Esri/esri-leaflet/issues/1196)

It looks like it should be resolved though.

**Comment by gavinr** [comment]
Hi, thanks for the report. Can you please post a replication (using jsbin, for example), that shows the issue you're referring to? Thanks!

**Comment by francharbo** [comment]
Hello,

I'm using esri-leaflet 2.5.1, leaflet 1.7.1, leaflet.markercluster 1.5.3 and esri-leaflet-cluster 2.1.0

However, using that configuration in jsbin i get this error : 
![image](https://user-images.githubusercontent.com/6029388/161218496-ada73d2c-b23a-4927-9759-36b18513aaeb.png)

So this will be quite hard to show you.
However I can share you some code

```javascript
   var map = L.map('map').setView([45.526, -122.667], 6);

  L.esri.basemapLayer('Streets').addTo(map);
  const layer = L.esri.Cluster.featureLayer({
    url: 'https://sampleserver6.arcgisonline.com/arcgis/rest/services/USA/MapServer/0',
    fetchAllfeatures: true
  }).addTo(map);
  
  layer.setWhere('pop2000 >= 15000')
```

**Comment by gavinr** [comment]
Here is a working sample with that code: https://jsbin.com/kapifomovi/edit?html,output

**Comment by francharbo** [comment]
Thank you for your quick responses !

I may have done something terribly stupid on my side !
I'll look into it and let you know

Update : 

Indeed the mistake was in my code.
This is working just fine :)
