### ISSUE TITLE
Leaflet 1.9.3 error - can't access property "properties", layer.feature is undefined

### ISSUE THREAD

**Issue by PedroVenancio** [Esri/esri-leaflet-cluster#60]
This issue was introduced with Leaflet 1.9.3 and affected bindPopup and bindTooltip of `L.esri.featureLayer`, as described here: https://github.com/Esri/esri-leaflet/issues/1348

It was fixed by https://github.com/Esri/esri-leaflet/pull/1350

but it also affects `L.esri.Cluster.featureLayer`, as you can see in this sample: https://codepen.io/PedroNGV/pen/QWBOpJd

`TypeError: can't access property "properties", layer.feature is undefined`

https://github.com/Esri/esri-leaflet/issues/1348#issuecomment-1396998637

**Comment by patrickarlt** [comment]
@gavinr could you apply the same fix I did for `L.esri.FeatureLayer` and see if that fixes this for cluster as well?

**Comment by gavinr** [comment]
The fix for this was released in [v3.0.1](https://github.com/Esri/esri-leaflet-cluster/releases/tag/v3.0.1).
